print('===Bem vindo a Localiza BR===')
dias = int(input('Quantos dias você passou com o carro? '))
km = float(input('Quantos km o carro andou? '))
total = (60 * dias) + (0.15 * km)
print(' O total a ser pago é de {:.2f}.'.format(total))