n = str(input('Digite seu nome completo: ')).strip()
nome = n.split()
print('Seu primeiro nome é: {}'.format(nome[0]))
print('Seu último nome é: {}'.format(nome[len(nome)-1]))
print('É um grande prazer estar aqui com você, {} {}! Volte sempre, meu/minha caro(a).'.format((nome[0]), (nome[len(nome)-1])))