print('---Seja bem-vindo ao programa de testes---')
algo = input('digite algo aqui: ')
print('O tipo primitivo do que você digitou é:', type(algo))
print('                                   ')
print('É um número?', algo.isnumeric())
print('É alfanumérico?', algo.isalnum())
print('Só tem espaços?', algo.isspace())
print('É alfabético?', algo.isalpha())
print('Está em maiúsculo?,', algo.isupper())
print('Está capializada?', algo.istitle())
print('Gostou? Deixe o like aí.')